# Generated by Django 5.0.7 on 2024-08-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent_type',
            field=models.CharField(blank=True, choices=[('t', 'Thread'), ('p', 'Post')], max_length=1),
        ),
    ]
