# Generated by Django 5.0.7 on 2024-08-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_parent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent_type',
            field=models.CharField(blank=True, choices=[('t', 'Thread'), ('p', 'Post'), ('c', 'Comment')], max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('t', 'Thread'), ('p', 'Post'), ('c', 'Comment')], max_length=1),
        ),
    ]
