# Generated by Django 5.0.7 on 2024-08-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_parent_type_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='posts.tag'),
        ),
    ]
