# Generated by Django 5.0.7 on 2024-08-02 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_parent_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_posts', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent_type',
            field=models.CharField(blank=True, choices=[('t', 'Thread'), ('p', 'Post'), ('c', 'Comment')], max_length=1, null=True),
        ),
    ]
